"""empty message

Revision ID: 491db3c31b95
Revises: 67f5d67aea55
Create Date: 2024-04-13 10:49:21.309607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491db3c31b95'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
